[versions]
agp = "8.7.3"
kotlin = "1.9.0"

commons-math3 = "3.6.1"
pedro = "1.0.0"
ftc = "10.1.1"
dokka = "1.9.24"

module-pedro = "0.5.1-beta2"
module-ftc = "0.5.1-beta2"
module-core = "0.5.1-beta2"

[libraries]
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
pedro = { module = "com.pedropathing:pedro", version.ref = "pedro" }
ftc-robotcore = { group = "org.firstinspires.ftc", name="RobotCore", version.ref = "ftc" }
ftc-hardware = { group = "org.firstinspires.ftc", name="Hardware", version.ref = "ftc" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }